version: '3'

services:
  postgres:
    image: postgres:13.3
    expose:
      - 5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: statistics
  
  server:
    build: .
    command: bash -c 'sleep 10 && cd ./app && uvicorn main:app --host 0.0.0.0'
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - STATS_DATABASE_URL=postgresql://root:root@postgres:5432/statistics
